parameters:
    logoFolder: '%kernel.project_dir%/public/logo'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\State\TeamLogoStateProvider:
        bind:
            $collectionProvider: '@api_platform.doctrine.orm.state.collection_provider'
            $itemProvider: '@api_platform.doctrine.orm.state.item_provider'

    App\State\UserPasswordStateProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
